"""
WitnessAI — PDF Incident Report Generator
Produces a professional, court-ready PDF report for every incident.
"""
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


def generate_incident_pdf(incident, output_path: Path) -> bool:
    """
    Generate a PDF incident report from an IncidentReport object.

    Args:
        incident: IncidentReport pydantic model
        output_path: Where to save the PDF

    Returns:
        True if successful, False otherwise.
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table,
            TableStyle, HRFlowable, Preformatted
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        logger.error("reportlab not installed; skipping PDF generation")
        return False

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path), pagesize=letter,
        leftMargin=0.9 * inch, rightMargin=0.9 * inch,
        topMargin=0.9 * inch, bottomMargin=0.9 * inch
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title", fontSize=20, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1a1a2e"), spaceAfter=6, alignment=TA_CENTER
    )
    sub_style = ParagraphStyle(
        "Sub", fontSize=10, fontName="Helvetica",
        textColor=colors.HexColor("#555555"), spaceAfter=4, alignment=TA_CENTER
    )
    h1_style = ParagraphStyle(
        "H1", fontSize=13, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1a1a2e"), spaceBefore=14, spaceAfter=4
    )
    body_style = ParagraphStyle(
        "Body", fontSize=9.5, fontName="Helvetica",
        textColor=colors.HexColor("#333333"), spaceAfter=5, leading=14
    )
    code_style = ParagraphStyle(
        "Code", fontSize=8, fontName="Courier",
        textColor=colors.HexColor("#1e293b"),
        backColor=colors.HexColor("#f1f5f9"),
        leftIndent=10, spaceAfter=4, leading=12
    )
    red_style = ParagraphStyle(
        "Red", fontSize=10, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#dc2626"), spaceAfter=6
    )

    def tbl(headers, rows, col_widths=None):
        data = [headers] + rows
        n = len(headers)
        cw = col_widths or [(6.6 * inch / n)] * n
        t = Table(data, colWidths=cw)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        return t

    story = []

    # Header
    story.append(Paragraph("⚠ WITNESSAI INCIDENT REPORT", title_style))
    story.append(Paragraph("Generated by WitnessAI — Real-Time Crime Scene Intelligence", sub_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#dc2626"), spaceAfter=10))

    # Incident meta
    story.append(Paragraph("Incident Summary", h1_style))
    meta_rows = [
        ["Incident ID", incident.incident_id],
        ["Feed", incident.feed_name or incident.feed_id],
        ["Anomaly Type", incident.anomaly_type.value.upper().replace("_", " ")],
        ["Triggered At", incident.triggered_at.strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Status", incident.status.value.upper()],
        ["Confidence Score", f"{incident.confidence_score:.1%}"],
        ["Tracks Involved", ", ".join(str(t) for t in incident.track_ids_involved) or "N/A"],
        ["Video Clip", incident.clip_path or "Not available"],
    ]
    story.append(tbl(["Field", "Value"], meta_rows, [2.2 * inch, 4.4 * inch]))
    story.append(Spacer(1, 0.1 * inch))

    # Scene summary
    if incident.scene_summary:
        story.append(Paragraph("Scene Summary (AI Generated)", h1_style))
        story.append(Paragraph(incident.scene_summary, body_style))

    # Narrative log
    if incident.narrative_log:
        story.append(Paragraph("Real-Time Incident Narrative", h1_style))
        for entry in incident.narrative_log:
            ts = entry.timestamp.strftime("%H:%M:%S")
            prefix = "⚠ ANOMALY — " if entry.is_anomaly else ""
            style = red_style if entry.is_anomaly else body_style
            story.append(Paragraph(f"[{ts}] {prefix}{entry.text}", style))

    # Footer
    story.append(Spacer(1, 0.3 * inch))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1")))
    story.append(Spacer(1, 0.08 * inch))
    generated = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    story.append(Paragraph(
        f"<i>Report generated automatically by WitnessAI on {generated}. "
        "This report is AI-generated and should be reviewed by a qualified professional before use in legal proceedings.</i>",
        ParagraphStyle("footer", fontSize=7.5, fontName="Helvetica",
                       textColor=colors.HexColor("#999999"), alignment=TA_CENTER)
    ))

    doc.build(story)
    logger.info(f"PDF report saved: {output_path}")
    return True
